from __future__ import annotations

from typing import Any, Dict, List, Optional

from mcp.server.fastmcp import FastMCP
from mangum import Mangum

from . import bedrock_client, dynamo_client, observatory

mcp = FastMCP(
    "DataDictionary",
    instructions=(
        "A DataDictionary MCP server that stores API field definitions (data elements) with "
        "AI-grounded meanings. Use propose_data_element to generate and propose a new entry "
        "from a natural language description, then commit_data_element to persist it. "
        "All read tools work without a commit step."
    ),
)


# ---------------------------------------------------------------------------
# Write tools — Propose + Commit via MCP Observatory
# ---------------------------------------------------------------------------


@mcp.tool(
    description=(
        "Generate a DataDictionary entry from a natural language description using an AI model, "
        "then propose it for storage. Returns a proposal_id and commit_token if approved. "
        "Call commit_data_element with those values to persist to DynamoDB."
    )
)
async def propose_data_element(prompt: str) -> Dict[str, Any]:
    """Propose a new or updated DataDictionary entry.

    Args:
        prompt: Natural language description of the API field.
                Example: 'customerId is a UUID v4 identifier assigned to a customer
                at account creation in the Orders API, immutable.'

    Returns:
        status: 'allowed' or 'blocked'
        proposal_id: ID to pass to commit_data_element
        commit_token: Token to pass to commit_data_element (only when allowed)
        generated_element: The DataElement JSON generated by the AI model
        signals: Risk signals from MCP Observatory
    """
    element = await bedrock_client.generate_data_element(prompt)
    tool_args = element.model_dump(exclude={"createdAt", "updatedAt"})

    result = await observatory.propose(
        tool_name="commit_data_element",
        tool_args=tool_args,
        prompt=prompt,
    )

    return {
        "status": result.get("status"),
        "proposal_id": result.get("proposal_id"),
        "commit_token": result.get("commit_token"),
        "generated_element": element.model_dump(),
        "signals": result.get("signals", {}),
    }


@mcp.tool(
    description=(
        "Commit a previously proposed DataDictionary entry to DynamoDB. "
        "Requires the proposal_id and commit_token returned by propose_data_element."
    )
)
async def commit_data_element(proposal_id: str, commit_token: str) -> Dict[str, Any]:
    """Persist a proposed DataDictionary entry to DynamoDB.

    Args:
        proposal_id: The proposal ID returned by propose_data_element.
        commit_token: The commit token returned by propose_data_element.

    Returns:
        dataElement: The key that was stored.
        updatedAt: ISO-8601 timestamp of the write.
        status: 'committed' on success.
    """
    proposal = await observatory.get_proposal(proposal_id)
    if not proposal:
        return {"error": f"Proposal '{proposal_id}' not found or expired."}

    tool_args: Dict[str, Any] = proposal.get("tool_args", {})
    tool_name = proposal.get("tool_name", "commit_data_element")
    verification = observatory.verify(proposal_id, commit_token, tool_name, tool_args)
    if not verification.ok:
        return {
            "error": "Commit verification failed.",
            "reason": getattr(verification, "failure_reason", "unknown"),
        }

    from .models import DataElement

    element = DataElement.model_validate(tool_args)
    saved = dynamo_client.put_data_element(element)
    return {
        "status": "committed",
        "dataElement": saved["dataElement"],
        "updatedAt": saved.get("updatedAt"),
    }


# ---------------------------------------------------------------------------
# Read tools — Direct DynamoDB
# ---------------------------------------------------------------------------


@mcp.tool(
    description=(
        "Retrieve a DataDictionary entry by its exact API field key name "
        "(e.g. 'customerId', 'order_total'). Returns the full definition."
    )
)
async def get_data_element(dataElement: str) -> Dict[str, Any]:
    """Fetch a data element definition by its exact key name.

    Args:
        dataElement: The exact API field key (case-sensitive).

    Returns:
        The DataElement record, or an error message if not found.
    """
    item = dynamo_client.get_data_element(dataElement)
    if not item:
        return {"error": f"Data element '{dataElement}' not found in the dictionary."}
    return item


@mcp.tool(
    description=(
        "Search the DataDictionary for entries whose key name or meaning contains the query string. "
        "Useful for discovering what fields exist for a concept (e.g. 'customer identifier')."
    )
)
async def search_data_elements(query: str) -> List[Dict[str, Any]]:
    """Search data elements by key name or meaning.

    Args:
        query: Free-text search string. Matched against dataElement and meaning fields.

    Returns:
        List of matching DataElement records.
    """
    return dynamo_client.search_data_elements(query)


@mcp.tool(
    description=(
        "List DataDictionary entries with optional context filter and pagination. "
        "Use context to scope results to a specific API or service."
    )
)
async def list_data_elements(
    context: Optional[str] = None,
    limit: int = 50,
    last_evaluated_key: Optional[str] = None,
) -> Dict[str, Any]:
    """List data elements, optionally filtered by context.

    Args:
        context: Optional API/service name to filter by (e.g. 'OrdersAPI').
        limit: Maximum number of items to return (default 50, max 100).
        last_evaluated_key: Pagination token from a previous response's next_key.

    Returns:
        items: List of DataElement records.
        next_key: Pagination token for the next page (null if no more results).
        count: Number of items returned.
    """
    import json

    lek = json.loads(last_evaluated_key) if last_evaluated_key else None
    capped_limit = min(limit, 100)
    return dynamo_client.list_data_elements(
        context=context, limit=capped_limit, last_evaluated_key=lek
    )


@mcp.tool(
    description=(
        "Retrieve all DataDictionary entries belonging to a specific API or service context "
        "(e.g. 'OrdersAPI', 'CustomerService'). Returns complete definitions for every field."
    )
)
async def get_elements_by_context(context: str) -> List[Dict[str, Any]]:
    """Get all data elements for a given API or service context.

    Args:
        context: The API or service name (e.g. 'OrdersAPI').

    Returns:
        List of all DataElement records belonging to that context.
    """
    items = dynamo_client.get_elements_by_context(context)
    if not items:
        return [{"message": f"No data elements found for context '{context}'."}]
    return items


# ---------------------------------------------------------------------------
# Lambda entry point via Mangum
# ---------------------------------------------------------------------------

_asgi_app = mcp.streamable_http_app(stateless_http=True)
# Keep ASGI lifespan enabled so FastMCP can initialize its StreamableHTTP
# session manager task group on startup.
lambda_handler = Mangum(_asgi_app, lifespan="auto")
